/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YjB48ZdTiOS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Prata } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function doc() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 shadow-sm">
        <div className="container mx-auto px-4 flex items-center justify-between">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CodeIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">API Docs</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link href="#" className="hover:underline" prefetch={false}>
              Introducción
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Endpoints
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Ejemplos
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Soporte
            </Link>
          </nav>
          <Button variant="secondary" size="sm">
            Probar API
          </Button>
        </div>
      </header>
      <main className="flex-1 py-12">
        <section id="introduction" className="container mx-auto px-4 mb-16">
          <h1 className="text-4xl font-bold mb-4">Bienvenido a la API</h1>
          <p className="text-muted-foreground text-lg mb-8">
            Explore nuestra poderosa API para integrar nuestros servicios en tu aplicación.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h2 className="text-2xl font-bold mb-4">Introducción</h2>
              <p className="text-muted-foreground mb-4">
                Aprende sobre los conceptos básicos de nuestra API, cómo autenticarte y empezar a usarla.
              </p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Leer más
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <h2 className="text-2xl font-bold mb-4">Guía de inicio rápido</h2>
              <p className="text-muted-foreground mb-4">
                Sigue estos pasos sencillos para comenzar a integrar nuestra API en tu aplicación.
              </p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Empezar
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>
        <section id="endpoints" className="container mx-auto px-4 mb-16">
          <h2 className="text-3xl font-bold mb-4">Endpoints</h2>
          <p className="text-muted-foreground text-lg mb-8">
            Explora los diferentes endpoints disponibles en nuestra API.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-2xl font-bold mb-4">Users</h3>
              <p className="text-muted-foreground mb-4">Accede a la información de los usuarios de tu aplicación.</p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Documentación
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">Products</h3>
              <p className="text-muted-foreground mb-4">Obtén información sobre los productos disponibles.</p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Documentación
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">Orders</h3>
              <p className="text-muted-foreground mb-4">Gestiona los pedidos de tus clientes.</p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Documentación
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">Payments</h3>
              <p className="text-muted-foreground mb-4">Integra los pagos de tus clientes.</p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Documentación
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>
        <section className="container mx-auto px-4 mb-16">
          <h2 className="text-3xl font-bold mb-4">Ejemplos de código</h2>
          <p className="text-muted-foreground text-lg mb-8">
            Mira algunos ejemplos de cómo integrar nuestra API en diferentes lenguajes y frameworks.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <div className="flex items-center gap-4 mb-4">
                <CodepenIcon className="h-8 w-8" />
                <h3 className="text-2xl font-bold">Next.js</h3>
              </div>
              <pre className="bg-muted p-4 rounded-md mb-4">
                <code>{`import { useEffect, useState } from 'react';

function UserList() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetch('/api/users', {
      headers: {
        'Authorization': 'Bearer your-api-key'
      }
    })
    .then(response => response.json())
    .then(data => setUsers(data));
  }, []);

  return (
    <ul>
      {users.map(user => (
        <li key={user.id}>{user.name}</li>
      ))}
    </ul>
  );
}`}</code>
              </pre>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Ver más
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <div className="flex items-center gap-4 mb-4">
                <CodepenIcon className="h-8 w-8" />
                <h3 className="text-2xl font-bold">Node.js</h3>
              </div>
              <pre className="bg-muted p-4 rounded-md mb-4">
                <code>{`const api = new API('your-api-key');
api.getUsers()
  .then(users => console.log(users))
  .catch(error => console.error(error));`}</code>
              </pre>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Ver más
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <div className="flex items-center gap-4 mb-4">
                <PiIcon className="h-8 w-8" />
                <h3 className="text-2xl font-bold">Python</h3>
              </div>
              <pre className="bg-muted p-4 rounded-md mb-4">
                <code>{`import requests

headers = {'Authorization': 'Bearer your-api-key'}
response = requests.get('https://api.example.com/users', headers=headers)
print(response.json())`}</code>
              </pre>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Ver más
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <div className="flex items-center gap-4 mb-4">
                <SmartphoneIcon className="h-8 w-8" />
                <h3 className="text-2xl font-bold">Android</h3>
              </div>
              <pre className="bg-muted p-4 rounded-md mb-4">
                <code>{`OkHttpClient client = new OkHttpClient();
Request request = new Request.Builder()
    .url("https://api.example.com/users")
    .addHeader("Authorization", "Bearer your-api-key")
    .build();

client.newCall(request).enqueue(new Callback() {
    @Override
    public void onResponse(Call call, Response response) throws IOException {
        // Handle the response
    }

    @Override
    public void onFailure(Call call, IOException e) {
        // Handle the error
    }
});`}</code>
              </pre>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Ver más
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>
        <section id="support" className="container mx-auto px-4 mb-16">
          <h2 className="text-3xl font-bold mb-4">Soporte</h2>
          <p className="text-muted-foreground text-lg mb-8">
            Si tienes alguna pregunta o necesitas ayuda, no dudes en contactarnos.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-2xl font-bold mb-4">Documentación</h3>
              <p className="text-muted-foreground mb-4">
                Consulta nuestra documentación detallada para obtener más información.
              </p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Ver documentación
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">Contacto</h3>
              <p className="text-muted-foreground mb-4">
                Si tienes alguna pregunta, no dudes en ponerte en contacto con nuestro equipo de soporte.
              </p>
              <Link href="#" className="inline-flex items-center gap-2 text-primary hover:underline" prefetch={false}>
                Contactar
                <ArrowRightIcon className="h-4 w-4" />
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6">
        <div className="container mx-auto px-4 flex items-center justify-between">
          <p className="text-sm">&copy; 2024 API Docs</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              Términos de servicio
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Política de privacidad
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function PiIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="9" x2="9" y1="4" y2="20" />
      <path d="M4 7c0-1.7 1.3-3 3-3h13" />
      <path d="M18 20c-1.7 0-3-1.3-3-3V4" />
    </svg>
  )
}


function SmartphoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}
